#!/usr/bin/env python

import numpy as np
import sys
import matplotlib.pyplot as plt
import scipy.signal as sig
import scipy.fftpack as fft
import argparse
from viterbi import viterbi,backtrace

def compute_sft(data, tsamp, Tsft, fh, bw, offset=0, padding_factor=1):
    print(len(data))
    count = int(Tsft/tsamp)
    
    data_to_sft = np.concatenate(((data[offset:offset+count] - np.mean(data[offset:offset+count])), np.zeros(int(count*(padding_factor-1)))))
    print(len(data_to_sft))
    ts = np.linspace(0, (len(data_to_sft)-1)*tsamp, len(data_to_sft))
    het_ts = np.exp(-1j*2*np.pi*fh*ts)


    het_data = het_ts * data_to_sft

    new_tsamp = 1./bw
    decim_factor = int(new_tsamp/tsamp)
    new_tsamp = tsamp*decim_factor

    #het_decim_data = het_data[::decim_factor]
    het_decim_data = sig.resample(het_data, int(count*padding_factor/decim_factor))

    if len(het_decim_data) % 2 == 1:
        het_decim_data = het_decim_data[:-1]

    het_data_fft = fft.fft(het_decim_data)

    norm = np.var(het_decim_data)*len(het_decim_data)
    
    fs = np.linspace(-bw/2, bw/2, len(het_decim_data))
    return 1/norm*np.abs(fft.fftshift(het_data_fft))**2, fs

if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--infile', type=str, help="Input data file (generated by PRESTO's `prepdata`)", required=True)
    parser.add_argument('--tsamp', type=float, help="Time series sampling period (in seconds)", required=True)
    parser.add_argument('--Tsft', type=float, help="Length of each Short Fourier Transform in the spectrogram (in seconds)", required=True)
    parser.add_argument('--Nsft', type=int, help="Number of SFTs to compute", required=False, default=-1)
    parser.add_argument('--f0', type=float, help="Bottom of the frequency band to be searched (in Hz)", required=True)
    parser.add_argument('--padding-factor', type=float, help="Pad with zeros to extend the duration of each Tsft by this factor", default=1)
    parser.add_argument('--bw', type=float, help="Width of the frequency band to be searched (in Hz)", required=True)
    parser.add_argument('--spec-flo', type=float, help="Lowest frequency included in spectrogram plot", required=False)
    parser.add_argument('--spec-fhi', type=float, help="Highest frequency included in spectrogram plot", required=False)
    parser.add_argument('--plot-path', help="Overplot best Viterbi path on spectrogram plot", action='store_true')
    parser.add_argument('--no-plot-path', help="Do not overplot best Viterbi path on spectrogram plot", action='store_false', dest='plot_path')
    parser.add_argument('--out_prefix', type=str, help="Prefix for output files", default="search")
    parser.add_argument('--top_paths', type=int, help="Save the top N paths and log likelihoods to {out_prefix}paths.dat", required=False, default=1)
    parser.add_argument('--save-delta', action='store_true', dest='save_delta')
    parser.add_argument('--num-harm', type=int, help="Number of harmonics to sum incoherently [default=1]", default=1)

    args = parser.parse_args()
    
    tsamp = args.tsamp
    data = np.fromfile(args.infile, dtype=np.single)
    Tfull = len(data)*tsamp
    Tsft = args.Tsft
    if args.Nsft == -1:
        Nsft = int(Tfull//Tsft)
    elif args.Nsft > 0:
        Nsft = args.Nsft
    else:
        print("--Nsft must be > 0!")
        exit()

    downsample_tsamp = tsamp
    decim_factor = int(downsample_tsamp/tsamp)
#    print(f"Pre-decimating by a factor {decim_factor}")

#    downsample_data = sig.resample(data, int(len(data)/decim_factor))
#    downsample_tsamp = Tfull/len(downsample_data)
#    print(f"New tsamp: {downsample_tsamp}")
    downsample_data = data

    bw = args.bw
    f0 = args.f0

    _, fs = compute_sft(downsample_data, downsample_tsamp, Tsft, f0 + bw/2., bw, padding_factor=args.padding_factor)
    spec = np.zeros((len(fs), Nsft), dtype=np.float)
    unsummed_spec = np.zeros((len(fs), args.num_harm), dtype=np.float)
    for i in range(0, Nsft):
        print(f"Doing timestep {i+1} of {Nsft}")
        for harm in range(1, args.num_harm+1):
            harm_spec, _ = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, (f0 + bw/2)*harm, bw*harm, offset=int(i*Tsft/downsample_tsamp), padding_factor=args.padding_factor))
            harm_spec = harm_spec[:harm*len(fs)]
            avgd_harm_spec = np.mean(harm_spec.reshape((-1, harm)), axis=1)
            unsummed_spec[:, harm-1] = avgd_harm_spec
        spec[:, i] = np.sum(unsummed_spec, axis=1)
        #spec[:, i], fs = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, f0, bw, offset=int(i*Tsft/downsample_tsamp), padding_factor=args.padding_factor))
        #spec[:, i], fs = compute_sft(data, tsamp, Tsft, f0, bw, offset=int(i*Tsft/tsamp))
        #second_harm, _ = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, 2*f0, 2*bw, offset=int(i*Tsft/downsample_tsamp)))
        #spec[:, i] += second_harm[:2*len(fs):2]

    fig, ax = plt.subplots()
    ax.imshow(spec, aspect='auto', extent=[0, Tfull, f0 + bw, f0], cmap='gray_r')
    ax.autoscale(False)

    delta, backptrs = viterbi(spec)


    if args.save_delta:
        np.savetxt(f"{args.out_prefix}_delta.dat", delta)

    top_n_delta_idxs = np.argsort(delta[:, -1])[-args.top_paths:]
    with open(f"{args.out_prefix}_paths.dat", "w") as f:
        for idx in top_n_delta_idxs:
            path = " ".join([str(x) for x in f0 + bw/2 + fs[backtrace(backptrs, idx)]])
            print(f"{delta[idx, -1]} {path}", file=f)

    path = f0 + bw/2 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]
    path = f0 + bw/2 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]
    print(path)
    print(args.plot_path)
    if args.plot_path:
        plt.plot(Tsft/2. + np.asarray(range(Nsft))*Tsft, path, 'r', linewidth=2)
        
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    if args.spec_flo is not None and args.spec_fhi is not None:
        plt.ylim(args.spec_flo, args.spec_fhi)
    plt.savefig(f'{args.out_prefix}_spectrogram.png', dpi=600)
    plt.clf()

    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Log likelihood')
    plt.plot(f0+bw/2+fs, delta[:, -1])
    plt.savefig(f'{args.out_prefix}_loglikes.png', dpi=600)
    #print(f"Score: {(np.max(delta[:, -1]) - np.mean(delta[:, -1]))/np.std(delta[:, -1])}")
    print(f"Loglike: {np.max(delta[:, -1])}")
