#!/usr/bin/env python

import numpy as np
import sys
import matplotlib.pyplot as plt
import scipy.signal as sig
import scipy.fftpack as fft
import argparse
from viterbi import viterbi,backtrace

def compute_sft(data, tsamp, Tsft, f0, bw, offset=0):
    count = int(Tsft/tsamp)
    
    fs = np.linspace(0, 1/2./tsamp, len(data)//2)

    data_fft = fft.fft(data)

    low_idx = int(np.floor(f0*2*tsamp) + len(data)//2)
    high_idx = int(np.ceil((f0+bw)*2*tsamp) + len(data)//2)

    norm = np.var(data)*len(data)

    return 1/norm*np.abs(fft.fftshift(data_fft)[low_idx:high_idx])**2, fs[low_idx:high_idx]

if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--infile', type=str, help="Input data file (generated by PRESTO's `prepdata`)", required=True)
    parser.add_argument('--tsamp', type=float, help="Time series sampling period (in seconds)", required=True)
    parser.add_argument('--Tsft', type=float, help="Length of each Short Fourier Transform in the spectrogram (in seconds)", required=True)
    parser.add_argument('--f0', type=float, help="Bottom of the frequency band to be searched (in Hz)", required=True)
    parser.add_argument('--bw', type=float, help="Width of the frequency band to be searched (in Hz)", required=True)
    parser.add_argument('--spec-flo', type=float, help="Lowest frequency included in spectrogram plot", required=False)
    parser.add_argument('--spec-fhi', type=float, help="Highest frequency included in spectrogram plot", required=False)
    parser.add_argument('--plot-path', help="Overplot best Viterbi path on spectrogram plot", action='store_true')
    parser.add_argument('--no-plot-path', help="Do not overplot best Viterbi path on spectrogram plot", action='store_false', dest='plot_path')
    parser.add_argument('--out_prefix', type=str, help="Prefix for output files", default="search")
    parser.add_argument('--save-delta', action='store_true', dest='save_delta')

    args = parser.parse_args()
    
    tsamp = args.tsamp
    data = np.fromfile(args.infile, dtype=np.single)
    Tfull = len(data)*tsamp
    Tsft = args.Tsft
    Nsft = int(Tfull/Tsft)

    downsample_tsamp = tsamp
    decim_factor = int(downsample_tsamp/tsamp)
#    print(f"Pre-decimating by a factor {decim_factor}")

#    downsample_data = sig.resample(data, int(len(data)/decim_factor))
#    downsample_tsamp = Tfull/len(downsample_data)
#    print(f"New tsamp: {downsample_tsamp}")
    downsample_data = data

    bw = args.bw
    f0 = args.f0

    _, fs = compute_sft(downsample_data, downsample_tsamp, Tsft, f0, bw)
    spec = np.zeros((len(fs), Nsft), dtype=np.float)

    for i in range(0, int(Tfull/Tsft)):
        print(f"Doing timestep {i+1} of {Nsft}")
        spec[:, i], fs = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, f0, bw, offset=int(i*Tsft/downsample_tsamp)))
        #spec[:, i], fs = compute_sft(data, tsamp, Tsft, f0, bw, offset=int(i*Tsft/tsamp))
        #second_harm, _ = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, 2*f0, 2*bw, offset=int(i*Tsft/downsample_tsamp)))
        #spec[:, i] += second_harm[:2*len(fs):2]

    fig, ax = plt.subplots()
    ax.imshow(spec, aspect='auto', extent=[0, Tfull, f0 + bw, f0])
    ax.autoscale(False)

    delta, backptrs = viterbi(spec)

    print(f"Score: {(np.max(delta[:, -1]) - np.mean(delta[:, -1]))/np.std(delta[:, -1])}")

    if args.save_delta:
        np.savetxt(f"{args.out_prefix}_delta.dat", spec[:, 1])

    path = f0 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]
    print(path)
    print(args.plot_path)
    if args.plot_path:
        plt.plot(Tsft/2. + np.asarray(range(Nsft))*Tsft, path, 'r', linewidth=2)
        
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    if args.spec_flo is not None and args.spec_fhi is not None:
        plt.ylim(args.spec_flo, args.spec_fhi)
    plt.savefig(f'{args.out_prefix}_spectrogram.png')
    plt.clf()

    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Log likelihood')
    plt.plot(f0+fs, delta[:, -1])
    plt.savefig(f'{args.out_prefix}_loglikes.png')
