#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import scipy.fftpack as fft
import argparse
import os
import configparser
import ast

from viterbi import viterbi, backtrace


"""
process_timeseries.py

This script performs a Viterbi-based search for a drifting narrowband signal
(e.g. a pulsar or continuous-wave signal) in a time-series dataset.

The pipeline operates as follows:

    1. Load a time-domain signal from a binary file.
    2. Divide the time series into segments of length Tsft.
    3. Compute a Short Fourier Transform (SFT) for each segment.
    4. Extract a specified frequency band [f0, f0 + bw] from each SFT.
    5. Assemble these spectra into a time–frequency spectrogram.
    6. Apply the Viterbi algorithm to identify the most likely frequency path
       through the spectrogram.

The Viterbi algorithm identifies the track that maximises the accumulated
log-likelihood across time, allowing detection of signals whose frequency
evolves slowly over time.

Inputs
------
The script accepts parameters either via command-line arguments or through
a parameter file using the --params option.

Required parameters include:

    infile : path to binary time-series file (float32 samples)
    tsamp  : sampling interval of the time series (seconds)
    Tsft   : duration of each SFT segment (seconds)
    f0     : lower bound of the frequency band to search (Hz)
    bw     : bandwidth of the search region (Hz)

Optional parameters control plotting and output behaviour.

Outputs
-------
The script produces:

    1. A spectrogram image showing power vs time and frequency
       (<out_prefix>_spectrogram.png)

    2. A plot of the final Viterbi log-likelihood distribution across
       frequency bins (<out_prefix>_loglikes.png)

Optionally it can also save the Viterbi delta matrix.

Notes
-----
This implementation assumes approximately stationary noise (homoscedastic
noise). A heteroscedastic variant of the pipeline would additionally
normalise the spectrogram by the local noise level before applying the
Viterbi search.
"""


def _load_params_file(path: str) -> dict:
    """Load key=value params file into a dict, converting types when possible."""
    if not path:
        return {}
    if not os.path.exists(path):
        raise FileNotFoundError(f"Params file not found: {path}")

    with open(path, "r") as f:
        raw = f.read()

    # configparser requires a section header
    raw = "[params]\n" + raw

    cfg = configparser.ConfigParser()
    cfg.optionxform = str  # preserve case sensitivity of keys
    cfg.read_string(raw)

    out = {}
    for k, v in cfg["params"].items():
        v = v.strip()
        try:
            out[k] = ast.literal_eval(v)
        except Exception:
            out[k] = v
    return out


def compute_sft(data, tsamp, Tsft, f0, bw, offset=0):
    """
    Compute a single SFT (power spectrum) for a segment of length Tsft starting at `offset`.

    Returns:
      band_power: array (Nf,)
      band_freqs: array (Nf,) in Hz
    """
    count = int(Tsft / tsamp)
    if count <= 0:
        raise ValueError(f"Invalid Tsft/tsamp: Tsft={Tsft}, tsamp={tsamp} => count={count}")

    # Extract the segment for this timestep
    seg = data[offset:offset + count]

    # If we run out of data, pad with zeros (so the pipeline still runs)
    if len(seg) == 0:
        return np.array([]), np.array([])

    if len(seg) < count:
        seg = np.pad(seg, (0, count - len(seg)))

    # Remove DC offset
    seg = seg - np.mean(seg)

    # FFT of the segment (not the entire dataset)
    seg_fft = fft.fft(seg)
    seg_fft = fft.fftshift(seg_fft)

    # Frequency axis aligned with fftshift output
    freqs = np.fft.fftfreq(len(seg), d=tsamp)
    freqs = fft.fftshift(freqs)

    # Select requested band [f0, f0 + bw]
    flo = f0
    fhi = f0 + bw
    band_mask = (freqs >= flo) & (freqs <= fhi)

    band_freqs = freqs[band_mask]

    # Simple normalised power (avoid divide-by-zero if variance is ~0)
    var = np.var(seg)
    norm = var * len(seg) if var > 0 else len(seg)

    band_power = (np.abs(seg_fft[band_mask]) ** 2) / norm

    return band_power, band_freqs


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    # Parameter-file support
    parser.add_argument('--params', type=str, help="Parameter file")

    # If using --params, these can be omitted on the CLI
    parser.add_argument('--infile', type=str, help="Input data file (generated by PRESTO's `prepdata`)")
    parser.add_argument('--tsamp', type=float, help="Time series sampling period (in seconds)")
    parser.add_argument('--Tsft', type=float, help="Length of each SFT in the spectrogram (in seconds)")
    parser.add_argument('--Nsft', type=int, help="Number of SFT timesteps (-1 = auto)")

    parser.add_argument('--f0', type=float, help="Bottom of the frequency band to be searched (in Hz)")
    parser.add_argument('--bw', type=float, help="Width of the frequency band to be searched (in Hz)")

    parser.add_argument('--spec-flo', type=float, help="Lowest frequency included in spectrogram plot")
    parser.add_argument('--spec-fhi', type=float, help="Highest frequency included in spectrogram plot")

    parser.add_argument('--plot-path', action='store_true')
    parser.add_argument('--no-plot-path', action='store_false', dest='plot_path')
    parser.set_defaults(plot_path=False)

    parser.add_argument('--out_prefix', type=str, default="search_homoscedastic")
    parser.add_argument('--save-delta', action='store_true', dest='save_delta')

    args = parser.parse_args()

    # Load params file then let CLI override it (CLI wins)
    params = _load_params_file(args.params)
    for k, v in params.items():
        if getattr(args, k, None) is None:
            setattr(args, k, v)

    # Required after merging params + CLI
    required = ['infile', 'tsamp', 'Tsft', 'f0', 'bw']
    missing = [k for k in required if getattr(args, k, None) is None]
    if missing:
        raise SystemExit(f"Missing required parameters (provide via --params or CLI): {missing}")

    tsamp = float(args.tsamp)
    Tsft = float(args.Tsft)
    f0 = float(args.f0)
    bw = float(args.bw)

    data = np.fromfile(args.infile, dtype=np.single)
    Tfull = len(data) * tsamp

    # Decide Nsft
    if getattr(args, "Nsft", None) is None:
        Nsft = int(Tfull / Tsft)
    else:
        Nsft = int(args.Nsft)
        if Nsft == -1:
            Nsft = int(Tfull / Tsft)

    # Build first SFT to size arrays
    p0, fs = compute_sft(data, tsamp, Tsft, f0, bw, offset=0)
    if len(fs) == 0:
        raise RuntimeError(
            "First SFT produced 0 frequency bins. "
            "Check (f0, bw) band and Tsft/tsamp."
        )

    spec = np.zeros((len(fs), Nsft), dtype=float)

    # Fill spectrogram
    count = int(Tsft / tsamp)
    for i in range(Nsft):
        offset = int(i * Tsft / tsamp)

        print(f"Doing timestep {i+1} of {Nsft}")

        p, fband = compute_sft(data, tsamp, Tsft, f0, bw, offset=offset)

        # If segment is empty (offset past end), stop cleanly
        if len(p) == 0:
            spec = spec[:, :i]  # trim unused columns
            Nsft = i
            break

        # Sanity: enforce consistent band length
        if len(p) != spec.shape[0]:
            raise RuntimeError(
                f"Inconsistent band size at timestep {i}: "
                f"got {len(p)} bins, expected {spec.shape[0]}. "
                "This usually means your band selection is changing; "
                "check compute_sft band logic."
            )

        spec[:, i] = p

    if spec.shape[1] == 0:
        raise RuntimeError("No timesteps were produced (spec has 0 columns). Reduce Tsft or use longer data.")

    # Plot spectrogram
    fig, ax = plt.subplots()
    ax.imshow(spec, aspect='auto', extent=[0, Nsft * Tsft, f0 + bw, f0])
    ax.autoscale(False)

    # Viterbi
    delta, backptrs = viterbi(spec)

    print(f"Score: {(np.max(delta[:, -1]) - np.mean(delta[:, -1]))/np.std(delta[:, -1])}")

    if args.save_delta:
        np.savetxt(f"{args.out_prefix}_delta.dat", delta)

    path = f0 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]
    print(path)
    print(args.plot_path)

    if args.plot_path:
        plt.plot(Tsft/2. + np.asarray(range(Nsft)) * Tsft, path, 'r', linewidth=2)

    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    if args.spec_flo is not None and args.spec_fhi is not None:
        plt.ylim(args.spec_flo, args.spec_fhi)
    plt.savefig(f'{args.out_prefix}_spectrogram.png')
    plt.clf()

    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Log likelihood')
    plt.plot(f0 + fs, delta[:, -1])
    plt.savefig(f'{args.out_prefix}_loglikes.png')