#!/usr/bin/env python

import numpy as np
import sys
import matplotlib.pyplot as plt
import scipy.signal as sig
import scipy.fftpack as fft
from scipy.optimize import curve_fit
import argparse
import configparser
import ast
import os
from viterbi import viterbi,backtrace



"""
process_timeseries_het.py

This script performs a Viterbi-based search for a drifting narrowband signal
(e.g. a pulsar or continuous-wave signal) in a time-series dataset, using a
heteroscedastic (time-varying noise) spectrogram statistic.

The pipeline operates as follows:

    1. Load a time-domain signal from a binary file.
    2. Divide the time series into segments of length Tsft.
    3. For each segment, compute a Short Fourier Transform (SFT) in a specified
       frequency band, using heterodyning and optional resampling/decimation.
    4. Assemble these per-segment spectra into a time–frequency spectrogram.
    5. Apply a heteroscedastic normalisation / likelihood construction so that
       each timestep is weighted by its local noise properties (i.e. the noise
       variance may change with time).
    6. Apply the Viterbi algorithm to identify the most likely frequency path
       through the resulting (noise-weighted) spectrogram.

The Viterbi algorithm identifies the track that maximises the accumulated
log-likelihood across time, allowing detection of signals whose frequency
evolves slowly over time.

Inputs
------
The script accepts parameters either via command-line arguments or through
a parameter file using the --params option.

Required parameters include:

    infile : path to binary time-series file (float32 samples)
    tsamp  : sampling interval of the time series (seconds)
    Tsft   : duration of each SFT segment (seconds)
    f0     : lower bound of the frequency band to search (Hz)
    bw     : bandwidth of the search region (Hz)

Optional parameters control harmonic handling, padding/resolution, plotting,
and output behaviour.

Outputs
-------
The script produces:

    1. A spectrogram image showing the heteroscedastic statistic vs time and
       frequency (<out_prefix>_spectrogram.png)

    2. A plot of the final Viterbi log-likelihood distribution across frequency
       bins (<out_prefix>_loglikes.png)

Optionally it can also save intermediate / diagnostic arrays (e.g. delta),
depending on runtime flags.

Notes
-----
This implementation explicitly accounts for heteroscedastic noise, meaning the
noise variance is allowed to change with time (and potentially across the
searched band). This reduces false structure from variable noise and improves
path scoring compared to a homoscedastic (constant-variance) assumption.
"""



def _load_params_file(path: str) -> dict:
    """
    Load key=value params file into a dict, converting types when possible.
    """
    if not path:
        return {}
    if not os.path.exists(path):
        raise FileNotFoundError(f"Params file not found: {path}")

    with open(path, "r") as f:
        raw = f.read()

    # configparser requires a section header
    raw = "[params]\n" + raw

    cfg = configparser.ConfigParser()
    cfg.optionxform = str  # preserve case sensitivity of keys
    cfg.read_string(raw)

    out = {}
    for k, v in cfg["params"].items():
        v = v.strip()
        try:
            out[k] = ast.literal_eval(v)  # floats/ints/bools/lists/strings-in-quotes
        except Exception:
            out[k] = v  # fallback: plain string
    return out

def compute_sft(data, tsamp, Tsft, fh, bw, offset=0, padding_factor=1):
    print(len(data))
    count = int(Tsft/tsamp)
    
    data_to_sft = np.concatenate(((data[offset:offset+count] - np.mean(data[offset:offset+count])), np.zeros(int(count*(padding_factor-1)))))
    print(len(data_to_sft))
    ts = np.linspace(0, (len(data_to_sft)-1)*tsamp, len(data_to_sft))
    het_ts = np.exp(-1j*2*np.pi*fh*ts)


    het_data = het_ts * data_to_sft

    new_tsamp = 1./bw
    decim_factor = int(new_tsamp/tsamp)
    new_tsamp = tsamp*decim_factor

    #het_decim_data = het_data[::decim_factor]
    het_decim_data = sig.resample(het_data, int(count*padding_factor/decim_factor))

    if len(het_decim_data) % 2 == 1:
        het_decim_data = het_decim_data[:-1]

    het_data_fft = fft.fft(het_decim_data)

    norm = np.var(het_decim_data)*len(het_decim_data)
    
    fs = np.linspace(-bw/2, bw/2, len(het_decim_data))
    return 1/norm*np.abs(fft.fftshift(het_data_fft))**2, fs

if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--infile', type=str, help="Input data file (generated by PRESTO's `prepdata`)")
    parser.add_argument('--tsamp', type=float, help="Time series sampling period (in seconds)")
    parser.add_argument('--Tsft', type=float, help="Length of each Short Fourier Transform in the spectrogram (in seconds)")
    parser.add_argument('--Nsft', type=int, help="Number of SFTs to compute", required=False, default=-1)
    parser.add_argument('--f0', type=float, help="Bottom of the frequency band to be searched (in Hz)")
    parser.add_argument('--padding-factor', type=float, help="Pad with zeros to extend the duration of each Tsft by this factor", default=1)
    parser.add_argument('--bw', type=float, help="Width of the frequency band to be searched (in Hz)")
    parser.add_argument('--spec-flo', type=float, help="Lowest frequency included in spectrogram plot", required=False)
    parser.add_argument('--spec-fhi', type=float, help="Highest frequency included in spectrogram plot", required=False)
    parser.add_argument('--plot-path', help="Overplot best Viterbi path on spectrogram plot", action='store_true')
    parser.add_argument('--no-plot-path', help="Do not overplot best Viterbi path on spectrogram plot", action='store_false', dest='plot_path')
    parser.add_argument('--out_prefix', type=str, help="Prefix for output files", default="search")
    parser.add_argument('--top_paths', type=int, help="Save the top N paths and log likelihoods to {out_prefix}paths.dat", required=False, default=1)
    parser.add_argument('--save-delta', action='store_true', dest='save_delta')
    parser.add_argument('--num-harm', type=int, help="Number of harmonics to sum incoherently [default=1]", default=1)
    parser.add_argument('--params', type=str, default=None,
                    help="Path to .params file (key = value). CLI args override params file.")
    
    # First pass: only to get --params
    pre_args, _ = parser.parse_known_args()

    # Load params from file and set as defaults
    params_dict = _load_params_file(pre_args.params)
    parser.set_defaults(**params_dict)

    # Second pass: parse again so CLI flags override file defaults
    args = parser.parse_args()

    # Validate required parameters after final parse
    required_fields = ['infile', 'tsamp', 'Tsft', 'f0', 'bw']
    missing = [field for field in required_fields if getattr(args, field) is None]
    if missing:
        raise ValueError(f"Missing required parameters: {missing}")

    tsamp = args.tsamp
    data = np.fromfile(args.infile, dtype=np.single)
    Tfull = len(data)*tsamp
    Tsft = args.Tsft
    if args.Nsft == -1:
        Nsft = int(Tfull//Tsft)
    elif args.Nsft > 0:
        Nsft = args.Nsft
    else:
        print("--Nsft must be > 0!")
        exit()

    downsample_tsamp = tsamp
    decim_factor = int(downsample_tsamp/tsamp)
#    print(f"Pre-decimating by a factor {decim_factor}")

#    downsample_data = sig.resample(data, int(len(data)/decim_factor))
#    downsample_tsamp = Tfull/len(downsample_data)
#    print(f"New tsamp: {downsample_tsamp}")
    downsample_data = data

    bw = args.bw
    f0 = args.f0

    _, fs = compute_sft(downsample_data, downsample_tsamp, Tsft, f0 + bw/2., bw, padding_factor=args.padding_factor)
    spec = np.zeros((len(fs), Nsft), dtype=float)
    unsummed_spec = np.zeros((len(fs), args.num_harm), dtype=float)
    for i in range(0, Nsft):
        print(f"Doing timestep {i+1} of {Nsft}")
        for harm in range(1, args.num_harm+1):
            harm_spec, _ = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, (f0 + bw/2)*harm, bw*harm, offset=int(i*Tsft/downsample_tsamp), padding_factor=args.padding_factor))
            harm_spec = harm_spec[:harm*len(fs)]
            avgd_harm_spec = np.mean(harm_spec.reshape((-1, harm)), axis=1)
            unsummed_spec[:, harm-1] = avgd_harm_spec
        spec[:, i] = np.sum(unsummed_spec, axis=1)
        #spec[:, i], fs = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, f0, bw, offset=int(i*Tsft/downsample_tsamp), padding_factor=args.padding_factor))
        #spec[:, i], fs = compute_sft(data, tsamp, Tsft, f0, bw, offset=int(i*Tsft/tsamp))
        #second_harm, _ = np.abs(compute_sft(downsample_data, downsample_tsamp, Tsft, 2*f0, 2*bw, offset=int(i*Tsft/downsample_tsamp)))
        #spec[:, i] += second_harm[:2*len(fs):2]

    fig, ax = plt.subplots()
    ax.imshow(spec, aspect='auto', extent=[0, Tfull, f0 + bw, f0], cmap='gray_r')
    ax.autoscale(False)

    delta, backptrs = viterbi(spec)


    if args.save_delta:
        np.savetxt(f"{args.out_prefix}_delta.dat", delta)

    top_n_delta_idxs = np.argsort(delta[:, -1])[-args.top_paths:]
    with open(f"{args.out_prefix}_paths.dat", "w") as f:
        for idx in top_n_delta_idxs:
            path = " ".join([str(x) for x in f0 + bw/2 + fs[backtrace(backptrs, idx)]])
            print(f"{delta[idx, -1]} {path}", file=f)

    path = f0 + bw/2 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]
    print(path)
    print(args.plot_path)






    # ###### Fit a quadratic to the best path to extract f0, f1, f2 at the reference time tref (middle of the track)
    # t = Tsft/2. + np.arange(Nsft)*Tsft
    # path = f0 + bw/2 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]

    # # choose reference index (middle)
    # imid = len(path)//2
    # tref = t[imid]

    # # take a small window around tref (e.g. ±5 points)
    # w = 5
    # ilo = max(0, imid - w)
    # ihi = min(len(path), imid + w + 1)

    # t_win = t[ilo:ihi]
    # f_win = path[ilo:ihi]

    # # shift time to tref
    # x = t_win - tref

    # # quadratic fit in local window
    # c2, c1, c0 = np.polyfit(x, f_win, 2)

    # f0_fit = c0
    # f1_fit = c1
    # f2_fit = 2*c2

    # print(f"Recovered f0 at tref={tref:.3f} s: {f0_fit:.12f} Hz")
    # print(f"Recovered f1: {f1_fit:.12e} Hz/s")
    # print(f"Recovered f2: {f2_fit:.12e} Hz/s^2")

    # # save full track
    # np.savetxt(
    #     f"{args.out_prefix}_track.dat",
    #     np.column_stack([t, path]),
    #     header="time_s frequency_hz"
    # )

    ###### Fit a sinusoid to the best path and extract local f0, f1, f2 at tref
    t = Tsft/2. + np.arange(Nsft) * Tsft
    path = f0 + bw/2 + fs[backtrace(backptrs, np.argmax(delta[:, -1]))]

    # choose reference time (middle of the track)
    imid = len(path) // 2
    tref = t[imid]

    # define sinusoidal model around tref
    def sin_model(t, fmean, amp, omega, phi):
        x = t - tref
        return fmean + amp * np.sin(omega * x + phi)

    # initial guesses
    fmean_guess = np.mean(path)
    amp_guess = 0.5 * (np.max(path) - np.min(path))

    # crude guess for angular frequency from one cycle over the observation
    Tobs = t[-1] - t[0] + Tsft
    omega_guess = 2.0 * np.pi / max(Tobs, Tsft)
    phi_guess = 0.0

    p0 = [fmean_guess, amp_guess, omega_guess, phi_guess]

    # bounds: positive amplitude, positive omega
    bounds = (
        [fmean_guess - 1.0, 0.0, 0.0, -2.0*np.pi],
        [fmean_guess + 1.0, 1.0, 1.0,  2.0*np.pi]
    )

    # fit
    popt, pcov = curve_fit(
        sin_model,
        t,
        path,
        p0=p0,
        bounds=bounds,
        maxfev=50000
    )

    fmean_fit, amp_fit, omega_fit, phi_fit = popt

    # evaluate local polynomial coefficients at tref
    # f(t) = f0 + f1*(t-tref) + 0.5*f2*(t-tref)^2 + ...
    f0_fit = fmean_fit + amp_fit * np.sin(phi_fit)
    f1_fit = amp_fit * omega_fit * np.cos(phi_fit)
    f2_fit = -amp_fit * omega_fit**2 * np.sin(phi_fit)

    # optional: fitted period of the sinusoid
    if omega_fit > 0:
        period_fit = 2.0 * np.pi / omega_fit
    else:
        period_fit = np.nan

    print(f"Recovered f0 at tref={tref:.3f} s: {f0_fit:.12f} Hz")
    print(f"Recovered f1: {f1_fit:.12e} Hz/s")
    print(f"Recovered f2: {f2_fit:.12e} Hz/s^2")
    print(f"Recovered sinusoid mean frequency: {fmean_fit:.12f} Hz")
    print(f"Recovered sinusoid amplitude: {amp_fit:.12e} Hz")
    print(f"Recovered sinusoid angular frequency: {omega_fit:.12e} rad/s")
    print(f"Recovered sinusoid period: {period_fit:.6f} s")
    print(f"Recovered sinusoid phase: {phi_fit:.12f} rad")

    # save fit parameters
    with open(f"{args.out_prefix}_sinusoid_fit.dat", "w") as f:
        f.write(f"tref_s {tref:.12f}\n")
        f.write(f"f0_at_tref_hz {f0_fit:.15f}\n")
        f.write(f"f1_at_tref_hz_per_s {f1_fit:.15e}\n")
        f.write(f"f2_at_tref_hz_per_s2 {f2_fit:.15e}\n")
        f.write(f"fmean_hz {fmean_fit:.15f}\n")
        f.write(f"amplitude_hz {amp_fit:.15e}\n")
        f.write(f"omega_rad_per_s {omega_fit:.15e}\n")
        f.write(f"period_s {period_fit:.15f}\n")
        f.write(f"phase_rad {phi_fit:.15f}\n")

    # save full track plus fitted model
    path_fit = sin_model(t, *popt)
    np.savetxt(
        f"{args.out_prefix}_track.dat",
        np.column_stack([t, path, path_fit]),
        header="time_s frequency_hz fitted_frequency_hz"
    )








    if args.plot_path:
        plt.plot(Tsft/2. + np.asarray(range(Nsft))*Tsft, path, 'r', linewidth=2)
        
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    if args.spec_flo is not None and args.spec_fhi is not None:
        plt.ylim(args.spec_flo, args.spec_fhi)
    plt.savefig(f'{args.out_prefix}_spectrogram_4_harmonics.png', dpi=600, bbox_inches='tight')
    plt.clf()

    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Log likelihood')
    plt.plot(f0+bw/2+fs, delta[:, -1])
    plt.savefig(f'{args.out_prefix}_loglikes_4_harmonics.png', dpi=600, bbox_inches='tight')
    #print(f"Score: {(np.max(delta[:, -1]) - np.mean(delta[:, -1]))/np.std(delta[:, -1])}")
    print(f"Loglike: {np.max(delta[:, -1])}")
